// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWGTJVE4L1XOUbLptJeYeM5lVOgkly0eM',
    appId: '1:465308159478:web:4b65ee142240acf7e54bd7',
    messagingSenderId: '465308159478',
    projectId: 'synapsepx',
    authDomain: 'synapsepx.firebaseapp.com',
    storageBucket: 'synapsepx.appspot.com',
    measurementId: 'G-HB497435SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChRmOcOKxWP_Nw-0D4UAI4aunJU5sZspI',
    appId: '1:465308159478:android:d822313c0d744bbbe54bd7',
    messagingSenderId: '465308159478',
    projectId: 'synapsepx',
    storageBucket: 'synapsepx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbingYn4Uw7P8zcjH9Do-4YZMBvNOnSx4',
    appId: '1:465308159478:ios:dd54264afa401fd9e54bd7',
    messagingSenderId: '465308159478',
    projectId: 'synapsepx',
    storageBucket: 'synapsepx.appspot.com',
    iosClientId: '465308159478-ahi88qp9iqb28enbdqf2ukuis9fm0ltj.apps.googleusercontent.com',
    iosBundleId: 'com.example.synapserxPatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbingYn4Uw7P8zcjH9Do-4YZMBvNOnSx4',
    appId: '1:465308159478:ios:dd54264afa401fd9e54bd7',
    messagingSenderId: '465308159478',
    projectId: 'synapsepx',
    storageBucket: 'synapsepx.appspot.com',
    iosClientId: '465308159478-ahi88qp9iqb28enbdqf2ukuis9fm0ltj.apps.googleusercontent.com',
    iosBundleId: 'com.example.synapserxPatient',
  );
}
